export const ERROR_CODES = {
	PHONE_TAKEN: "PHONE_TAKEN",
	EMAIL_TAKEN: "EMAIL_TAKEN",
	UNAUTHORIZED: "UNAUTHORIZED",
	CLERK_ID_TAKEN: "CLERK_ID_TAKEN",
	USER_NOT_FOUND: "USER_NOT_FOUND",
	UPLOAD_FAILED: "UPLOAD_FAILED",
	USER_CREATION_FAILED: "USER_CREATION_FAILED",
	PUSH_NOTIFICATION_FAILED: "PUSH_NOTIFICATION_FAILED",
};
