export const ERROR_CODES = {
	PHONE_TAKEN: "PHONE_TAKEN",
	EMAIL_TAKEN: "EMAIL_TAKEN",
	UNAUTHORIZED: "UNAUTHORIZED",
	UPLOAD_FAILED: "UPLOAD_FAILED",
	DOWNLOAD_FAILED: "DOWNLOAD_FAILED",
	AUTH: {
		RESEND_CODE_FAILED: "RESEND_CODE_FAILED",
		VERIFY_CODE_FAILED: "VERIFY_CODE_FAILED",
		AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
	},
	USER: {
		NOT_FOUND: "USER_NOT_FOUND",
		UPDATE_FAILED: "USER_UPDATE_FAILED",
		CREATION_FAILED: "USER_CREATION_FAILED",
		RETRIEVAL_FAILED: "USER_RETRIEVAL_FAILED",
	},
};
