import {
  BellIcon,
  BetweenHorizontalEndIcon,
  CalendarIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ChevronsUpDownIcon,
  ChevronUpIcon,
  EditIcon,
  EyeIcon,
  EyeOffIcon,
  GlobeIcon,
  HomeIcon,
  CarIcon as LucideCarIcon,
  type LucideIcon,
  MessageSquareIcon,
  MoonIcon,
  MoveLeftIcon,
  PaletteIcon,
  PlusIcon,
  Rows3Icon,
  SearchIcon,
  SmartphoneIcon,
  SunIcon,
  TrashIcon,
  UploadIcon,
  XIcon,
} from "lucide-react-native";
import { CarIcon } from "./car";
import { EnFlag, MoldovaStema, RoFlag, RuFlag, TransnistriaFlag } from "./flags";
import { iconWithClassName } from "./icon-w-classname";
import { SwipeLeftIcon } from "./swipe-left";
import { SwipeRightIcon } from "./swipe-right";

// Apply cssInterop to each icon
[
  RoFlag as unknown as LucideIcon,
  RuFlag as unknown as LucideIcon,
  EnFlag as unknown as LucideIcon,
  MoldovaStema as unknown as LucideIcon,
  TransnistriaFlag as unknown as LucideIcon,
  CarIcon as unknown as LucideIcon,
  SwipeLeftIcon as unknown as LucideIcon,
  SwipeRightIcon as unknown as LucideIcon,
  MoonIcon,
  LucideCarIcon,
  MoveLeftIcon,
  SunIcon,
  GlobeIcon,
  CheckIcon,
  HomeIcon,
  XIcon,
  BetweenHorizontalEndIcon,
  ChevronsUpDownIcon,
  SearchIcon,
  CalendarIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  UploadIcon,
  EyeIcon,
  BellIcon,
  PaletteIcon,
  PlusIcon,
  EyeOffIcon,
  Rows3Icon,
  ChevronRightIcon,
  EditIcon,
  TrashIcon,
  SmartphoneIcon,
  MessageSquareIcon,
].forEach(iconWithClassName);

export {
  MoonIcon,
  SunIcon,
  GlobeIcon,
  CheckIcon,
  HomeIcon,
  XIcon,
  LucideCarIcon,
  ChevronsUpDownIcon,
  SearchIcon,
  CalendarIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  EyeIcon,
  EyeOffIcon,
  PaletteIcon,
  RoFlag,
  RuFlag,
  EnFlag,
  MoldovaStema,
  TransnistriaFlag,
  CarIcon,
  BellIcon,
  UploadIcon,
  SwipeLeftIcon,
  SwipeRightIcon,
  PlusIcon,
  EditIcon,
  Rows3Icon,
  ChevronRightIcon,
  TrashIcon,
  BetweenHorizontalEndIcon,
  MoveLeftIcon,
  MessageSquareIcon,
  SmartphoneIcon,
};
